---
title: "Visualizations"
author: "Ryan Southward"
date: "2022-07-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(gganimate)
library(usmap)
setwd("~/Desktop/Personal-Projects/gun-violence")
```

```{r}
data <- read_rds("data/consolidated/combined2010to2020.rds")

filtered1 <- data |>
  filter(! Recovery_State %in% c("VIRGIN ISLANDS", "TOTAL", "GUAM", "CANADA")) |>
  filter(Source_State != "TOTAL") |>
  group_by(Year, Recovery_State) |>
  filter(Guns_Recovered > quantile(Guns_Recovered, probs = .9)) |>
  ungroup() |>
  pivot_wider(names_from = Year, values_from = Guns_Recovered, values_fill = 0) |>
  arrange(Recovery_State)
```

```{r}
# filtered2 <- data |>
#   filter(Source_State == Recovery_State) |>
#   drop_na(Guns_Recovered) |>
#   pivot_wider(names_from = Year, values_from = Guns_Recovered) |>
#   na.omit()
```


```{r}

filtered2 <- filtered1 |>
      filter(Recovery_State == "ALABAMA") |>
      select(Source_FIPS, "2014") |>
      mutate(GEOID = as.character(Source_FIPS))

    map <- plot_usmap(data = filtered2, regions = "states") +
      scale_fill_viridis_c()
    
  plot_gg(map)

  render_snapshot()
```

```{r}
us <- read_sf("data/us") |>
  



#geo <- left_join(us, filtered2, by = "GEOID") 
#geo[is.na(geo)] <- 0

doc <- geo |> filter(NAME == "District of Columbia")

geo <- geo|>
  filter(!NAME %in% c("Puerto Rico", "Guam", "United States Virgin Islands", "Commonwealth of the Northern Mariana Islands", "American Samoa", "District of Columbia")) |>
  arrange(NAME)

  mutate(policy = sample.int(n = 6, size = 49, replace = TRUE), Center_x = state.center$x, Center_y = state.center$y)

ggplot(data = us) +
  geom_sf()
  
```


```{r}
library(rnaturalearth)
library(geosphere)


states <- ne_states(iso_a2 = 'US') 
states@data$name <- toupper(states@data$name)

names <- states@data$name
data <- read_rds("data/consolidated/combined2010to2020.rds") |>
group_by(Year, Recovery_State) |>
filter(Guns_Recovered > quantile(Guns_Recovered, probs = .9)) |>
ungroup()

coords <- states@data |> select(name, longitude, latitude) 

# Rename lat and long cols to reference Source/Recovery. Makes merge easier later on.  
Recovery_coords <- coords |> rename(Recovery_long = longitude, Recovery_lat = latitude)
Source_coords <- coords |> rename(Source_long = longitude, Source_lat = latitude)

# Cross reference - start with Source/Recovery State name, and compare to name in coords

 mainland <- data |> 
   filter(Recovery_State %in% names) |>
   filter(Source_State %in% names)

mainland <- left_join(mainland, Recovery_coords, by = c("Recovery_State" = "name"))
mainland <- left_join(mainland, Source_coords, by = c("Source_State" = "name")) 

#Create Great Circles
flows <- gcIntermediate(mainland[,5:6], mainland[,7:8], sp = TRUE, addStartEnd = TRUE)
flows$Recovery_State <- mainland$Recovery_State
flows$Source_State <- mainland$Source_State
flows$Guns_Recovered <- mainland$Guns_Recovered

```


```{r}
library(leaflet)
library(RColorBrewer)

# Create leaflet graph

#origins
hover <- paste0(flows$Source_State, " to ", 
#destinations
                flows$Recovery_State, ': ', 
                as.character(flows$Guns_Recovered))

pal <- colorFactor(brewer.pal(4, 'Set2'), flows$Source_State)

leaflet() %>%
  addProviderTiles('CartoDB.Positron') %>%
  addPolylines(data = flows, weight = ~Guns_Recovered, label = hover, 
               group = ~Source_State, color = ~pal(Source_State)) %>%
  addLayersControl(overlayGroups = unique(flows$Source_State), 
                   options = layersControlOptions(collapsed = FALSE))
```
```{r}
library(urbnmapr)


ussf <- urbnmapr::get_urbn_map(map = 'territories_states')

data <- read_rds("data/consolidated/combined2010to2020.rds")

filtered <- data |>
  filter(Source_State != "Total", Recovery_State != 'Total') |>
  filter(Source_State != Recovery_State) |>
  group_by(Recovery_State, Year) |>
  arrange(desc(Guns_Recovered)) |>
  slice(1:8) |>
  ungroup() |>
  pivot_wider(names_from = Year, values_from = Guns_Recovered) 

combined <- left_join(filtered, get_urbn_labels(map = 'territories'), by = c('Source_State' = 'state_name')) |>
  filter(Recovery_State == "Illinois") 

ussf <- ussf |>
  mutate(is_colored = factor(if_else(state_name == "Illinois", 1, 0)))


ggplot() +
  geom_polygon(data = ussf, aes(x = long, y = lat, group = group, fill = is_colored), color = '#ffffff', size = .25) +
  scale_fill_manual(values = c('#C0C0C0', '#AF251F')) +
  geom_point(data = combined, aes(x = long, y = lat, size = `2010`), na.rm = TRUE) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  scale_size_area() +
  theme(panel.background = element_blank(), axis.title = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), legend.key=element_blank(), plot.caption = element_text(hjust = 0)) +
  guides(fill = "none") +
  labs(title = paste("Origins of Guns Recovered from", "Illinois", "in", "2010"),
       size = "Guns Sourced from State", 
       caption = "Source: Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF)") 

```

```{r}
ggplot(urbnmapr::states) +
  geom_polygon(aes(x = long, y = lat, group = group))

```

```{r}
library(maps)

us_geom <- map_data("state")

ggplot() + 
  geom_polygon( data=us_geom, aes(x=long, y=lat, group=group),
                color="black", fill="lightblue" )

```

```{r}
  library(maps)
  library(geosphere)
  library(dplyr)
  library(ggplot2)
  library(rworldmap)
  library(plyr)
  library(data.table)
  library(ggthemes)


# Get World map
  worldMap <- getMap()
  mapworld_df <- fortify( worldMap )


# Read data on airports and flights
  airports <- read.csv("http://www.stanford.edu/~cengel/cgi-bin/anthrospace/wp-content/uploads/2012/03/airports.csv", as.is=TRUE, header=TRUE)
  flights <- read.csv("http://www.stanford.edu/~cengel/cgi-bin/anthrospace/wp-content/uploads/2012/03/PEK-openflights-export-2012-03-19.csv", as.is=TRUE, header=TRUE)

# get airport locations
  airport_locations <- airports[, c("IATA","longitude", "latitude")]

# aggregate number of flights (frequency of flights per pair)
  flights.ag <- ddply(flights, c("From","To"), function(x) count(x$To))


# Link airport lat  long to origin and destination
  OD <- left_join(flights.ag, airport_locations, by=c("From"="IATA") )
  OD <- left_join(OD, airport_locations, by=c("To"="IATA") )
  OD$id <-as.character(c(1:nrow(OD))) #create and id for each pair



##### Two Simple Maps ##### 

# 1. Using straight lines
  ggplot() + 
    geom_polygon(data= mapworld_df, aes(long,lat, group=group), fill="gray30") +
    geom_segment(data = OD, aes(x = longitude.x, y = latitude.x, xend = longitude.y, yend = latitude.y, color=freq),
                 arrow = arrow(length = unit(0.01, "npc"))) +
    scale_colour_distiller(palette="Reds", name="Frequency", guide = "colorbar") +
    coord_equal()


# 2. Using Curved Lines
  ggplot() + 
    geom_polygon(data= mapworld_df, aes(long,lat, group=group), fill="gray30") +
    geom_curve(data = OD, aes(x = longitude.x, y = latitude.x, xend = longitude.y, yend = latitude.y, color=freq),
               curvature = -0.2, arrow = arrow(length = unit(0.01, "npc"))) +
    scale_colour_distiller(palette="Reds", name="Frequency", guide = "colorbar") +
    coord_equal()



##### A more professional map ####  
# Using shortest route between airports considering the spherical curvature of the planet

# get location of Origin and destinations airports
  setDT(OD) # set OD as a data.table for faster data manipulation
  beijing.loc <- OD[ From== "PEK", .(longitude.x, latitude.x)][1] # Origin
  dest.loc <- OD[ , .(longitude.y, latitude.y)] # Destinations

# calculate routes between Beijing (origin) and other airports (destinations)
  routes <- gcIntermediate(beijing.loc, dest.loc, 100, breakAtDateLine=FALSE, addStartEnd=TRUE, sp=TRUE)
  class(routes) # SpatialLines object


# Convert a SpatialLines object into SpatialLinesDataFrame, so we can fortify and use it in ggplot
  # create empty data frate  
  ids <- data.frame()
  # fill data frame with IDs for each line
  for (i in (1:length(routes))) {         
    id <- data.frame(routes@lines[[i]]@ID)
    ids <- rbind(ids, id)  }

  colnames(ids)[1] <- "ID" # rename ID column

# convert SpatialLines into SpatialLinesDataFrame using IDs as the data frame
  routes <- SpatialLinesDataFrame(routes, data = ids, match.ID = T)

# Fortify routes (convert to data frame)  +++  join attributes
  routes_df <- fortify(routes, region= "ID") # convert into something ggplot can plot
  gcircles <- left_join(routes_df, OD, by= ("id"))
  head(gcircles)

### Recenter ####

center <- 115 # positive values only - US centered view is 260

# shift coordinates to recenter great circles
  gcircles$long.recenter <-  ifelse(gcircles$long  < center - 180 , gcircles$long + 360, gcircles$long) 

# shift coordinates to recenter worldmap
  worldmap <- map_data ("world")
  worldmap$long.recenter <-  ifelse(worldmap$long  < center - 180 , worldmap$long + 360, worldmap$long)

### Function to regroup split lines and polygons
# takes dataframe, column with long and unique group variable, returns df with added column named group.regroup
  RegroupElements <- function(df, longcol, idcol){  
    g <- rep(1, length(df[,longcol]))
    if (diff(range(df[,longcol])) > 300) {          # check if longitude within group differs more than 300 deg, ie if element was split
      d <- df[,longcol] > mean(range(df[,longcol])) # we use the mean to help us separate the extreme values
      g[!d] <- 1     # some marker for parts that stay in place (we cheat here a little, as we do not take into account concave polygons)
      g[d] <- 2      # parts that are moved
    }
    g <-  paste(df[, idcol], g, sep=".") # attach to id to create unique group variable for the dataset
    df$group.regroup <- g
    df
  }

### Function to close regrouped polygons
# takes dataframe, checks if 1st and last longitude value are the same, if not, inserts first as last and reassigns order variable
  ClosePolygons <- function(df, longcol, ordercol){
    if (df[1,longcol] != df[nrow(df),longcol]) {
      tmp <- df[1,]
      df <- rbind(df,tmp)
    }
    o <- c(1: nrow(df))  # rassign the order variable
    df[,ordercol] <- o
    df
  }

# now regroup
  gcircles.rg <- ddply(gcircles, .(id), RegroupElements, "long.recenter", "id")
  worldmap.rg <- ddply(worldmap, .(group), RegroupElements, "long.recenter", "group")

# close polys
  worldmap.cp <- ddply(worldmap.rg, .(group.regroup), ClosePolygons, "long.recenter", "order")  # use the new grouping var



# Flat map
  ggplot() +
    geom_polygon(data=worldmap.cp, aes(long.recenter,lat,group=group.regroup), size = 0.2, fill="#f9f9f9", color = "grey65") +
    geom_line(data= gcircles.rg, aes(long.recenter,lat,group=group.regroup, color=freq), size=0.4, alpha= 0.5) +
    scale_colour_distiller(palette="Reds", name="Frequency", guide = "colorbar") +
    theme_map()+
    ylim(-60, 90) +
    coord_equal()


# Spherical Map
  ggplot() +
    geom_polygon(data=worldmap.cp, aes(long.recenter,lat,group=group.regroup), size = 0.2, fill="#f9f9f9", color = "grey65") +
    geom_line(data= gcircles.rg, aes(long.recenter,lat,group=group.regroup, color=freq), size=0.4, alpha= 0.5) +
    scale_colour_distiller(palette="Reds", name="Frequency", guide = "colorbar") +
    # Spherical element
    scale_y_continuous(breaks = (-2:2) * 30) +
    scale_x_continuous(breaks = (-4:4) * 45) +
    coord_map("ortho", orientation=c(61, 90, 0)) 
```

Per Capita experimentation

```{r}
input <- list()
input$numStates = 8
input$state = 'Illinois'
input$year = '2020'

data <- read_rds("data/consolidated/combined2010to2020.rds") |>
  #Change 'Total' (name attributed by ATF) to United States throughout df
  mutate(Recovery_State = if_else(Recovery_State == 'Total', 'United States', Recovery_State)) |>
  mutate(Source_State = if_else(Source_State == 'Total', 'United States', Source_State)) |>
  #Filter out Guam and Virigin Islands because of lack of available population data.
  filter(! Source_State %in% c("Guam", "Virgin Islands")) |>
  filter(! Recovery_State %in% c("Guam", "Virgin Islands"))

sum(is.na(data$Guns_Recovered))

#Adjust gun data to be per 100k people. 
pop_data <- read_rds("data/consolidated/state-populations-2010-2020.rds") |>
  pivot_longer(cols = `2010`:`2020`, names_to = "Year", values_to = "Population") |>
  mutate(Year = as.numeric(Year)) |>
  as.data.frame()

data <- left_join(data, pop_data, by = c('Source_State' = 'State', 'Year' = 'Year')) |>
  mutate(Guns_Recovered_PerCapita = (Guns_Recovered * 100000) / Population)

      filtered <- data |>
        filter(Recovery_State == input$state) |>
        filter(Source_State != 'United States') |>
        filter(Year == input$year) |>
        #filter(Source_State != Recovery_State) |>
        group_by(Recovery_State, Year) |>
        arrange(desc(Guns_Recovered)) |>
        slice(1:input$numStates) 

  


```

```{r}
library(rvest)
library(stringr)

#Create skeleton data frame with necessary column names
data <- data.frame(State_Name = NULL, Year = NULL, Provision_Name = NULL, Provision_Description = NULL, Current_Status = NULL)

#Map state abbreviations to names
names <- state.name
names(names) <- state.abb
  
for (state_abb in state.abb) {
  for (year in 2010:2018) {
    #Scrape provision data from (https://www.statefirearmlaws.org/)
    html <- read_html(paste("https://www.statefirearmlaws.org/states", state_abb, year, sep = "/")) 
    df <- data.frame(html |> html_elements('.provision-name') |> html_text2())
    df <- cbind(df, html |> html_elements('.provision-description') |> html_text2())
    df <- cbind(df, html |> html_elements('.provision-status') |> html_text2())
    #Replace spaces in col names with underscores
    df <- df |> row_to_names(row_number = 1) |>
      rename_with(.fn = ~ str_replace(., pattern = " ", replacement = "_"))
    #Add name and year identifying columns
    df <- df |> 
      add_column(State_Name = names[state_abb], .before = "Provision_Name") |>
      add_column(Year = year, .after = "State_Name")
    #Compile data
    data <- rbind(data, df)
  }
}
```


